### PR TITLE
add dynamic deploy path

### PR DESCRIPTION
**Pull request by masco**

### CODE REVIEW

**Comment by amitsagtani97** [comment]
hey @masco can we test these changes somewhere with post-install and config enabled?

**Comment by masco** [comment]
@amitsagtani97 tested https://jenkins.scalelab.redhat.com/job/ATS-SCALE-CI-OCP-OSP-DEPLOY/121/console

**Comment by amitsagtani97** [comment]
we need to check it with OPENSHIFT_POST_INSTALL set to true here https://jenkins.scalelab.redhat.com/job/ATS-SCALE-CI-OCP-OSP-DEPLOY/121/parameters/ 
OPENSHIFT_POST_CONFIG does not use DYNAMIC_DEPLOY_PATH :)

**Comment by masco** [comment]
@amitsagtani97 we are not using post-install from this repo, we have our own script on jetpack.

we are setting the DYNAMIC_DEPLOY_PATH and the kubeconfig_path on the main script https://github.com/cloud-bulldozer/scale-ci-deploy/blob/master/OCP-4.X/install-on-osp.yml#L21-L35

this will be used for all the roles including the POST_CONFIG. that is why our job is failing to fetch/set the kubeconfig.
so the test with the POST_CONFIG=true is enough for us to validate this PR.

Let me know if I am missing something.

**Review by chaitanyaenr — APPROVED** [review]
LGTM

**Comment by amitsagtani97** [comment]
> @amitsagtani97 we are not using post-install from this repo, we have our own script on jetpack.
> 
> we are setting the DYNAMIC_DEPLOY_PATH and the kubeconfig_path on the main script https://github.com/cloud-bulldozer/scale-ci-deploy/blob/master/OCP-4.X/install-on-osp.yml#L21-L35
> 
> this will be used for all the roles including the POST_CONFIG. that is why our job is failing to fetch/set the kubeconfig.
> so the test with the POST_CONFIG=true is enough for us to validate this PR.
> 
> Let me know if I am missing something.

@masco Makes sense. Looks good

**Review by amitsagtani97 — APPROVED** [review]
LGTM!

**Pull request merged**
