### PR TITLE
add jjb script for ROSA deployment

### PR DESCRIPTION
**Pull request by morenod**
Script to execute ROSA installations using a bastion host to run osde2e-wrapper.py script

### CODE REVIEW

**Comment by morenod** [comment]
Execution example

https://jenkins.scalelab.redhat.com/job/SCALE-CI-MS-ROSA/3/console

**Review by mohit-sheth — APPROVED** [review]
LGTM!

**Comment by dry923** [comment]
@morenod can we also add the option to set the expiration parameter?

**Comment by morenod** [comment]
> @morenod can we also add the option to set the expiration parameter?

Done

**Review by dry923 — APPROVED** [review]
LGTM!

**Review by chaitanyaenr — APPROVED** [review]
LGTM

**Pull request merged**
